[project]
name = "SNAPRed"
description = "A desktop application for Lifecycle Managment of data collected from the SNAP instrument."
dynamic = ["version"]
requires-python = ">=3.8"
dependencies = [
    "mantidworkbench"
]

[build-system]
requires = [
  "setuptools >= 42",
  "versioningit"
]
build-backend = "setuptools.build_meta"

[tool.versioningit.vcs]
method = "git"
default-tag = "0.0.1"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = [
  "./src"
]

[flake8]
max-line-length = 120
ignore = 'E203'

[[tool.mypy.overrides]]
module = [
    "yaml",
]
ignore_missing_imports = true
